### PR TITLE
Use `type` as the type of Inputs/Outputs fields

### PR DESCRIPTION
**Pull request by tpoliaw**

### CODE REVIEW

**Review by abbiemery — CHANGES_REQUESTED** [review]
LGTM, but there are a few complaints by mypy in the ci lint. Any chance you could sort these or if it looks to be a larger job `#ignore` it and make a separate issue for it.

**Comment by tpoliaw** [comment]
I've not found a useful way of getting mypy and pyright to agree on something that is valid when using `TypedDict` as a function. One alternative that both accept is to define Inputs and Outputs as nested classes.

```python
class AmplifierDevice(Device):
    class Inputs(TypedDict):
        initial_signal: float
    class Outputs(TypedDict):
        amplified_signal: float

    def __init__(self, init_amp: float = 2) -> None:
        self.amp = init_amp

    def update(self, time: SimTime, inputs: Inputs) -> DeviceUpdate[Outputs]:
        amp_val = inputs["initial_signal"] * self.amp
        return DeviceUpdate(self.Outputs(amplified_signal=amp_val), None)
```

I can't see any major differences that would prevent this form working but I'm not familiar with the innards of tickit.

**Comment by tpoliaw** [comment]
I think the mypy issues stem from https://github.com/python/mypy/issues/10851

**Comment by callumforrester** [comment]
@tpoliaw Does this support optional changes? Tickit expects all inputs/outputs to be optional, i.e. if you have
```python
class Inputs:
    foo: int
    bar: str
```

Then all of the following should be valid:
```python
{}
{"foo": 2}
{"bar": "baz"}
{"foo": 2, "bar": "baz"}
```

**Comment by tpoliaw** [comment]
> @tpoliaw Does this support optional changes? Tickit expects all inputs/outputs to be optional

No, but neither does the previous `Inputs = TypedDict('Input', {...})` syntax

**Comment by tpoliaw** [comment]
You can mark fields as optional using (eg) `NotRequired[int]` but this raises additional errors when accessing keys as they become typed as `Optional[int]`.

**Comment by callumforrester** [comment]
Hmm, this may break things then... The idea is that only new input/output values get sent between devices.

**Comment by callumforrester** [comment]
Example of mypy's insufficiency here: https://mypy-play.net/?mypy=latest&python=3.11&gist=7fa9d9104c4108b42da87ed04b378baa

Suggestion is moving to pyright.

**Pull request merged**
